---
title: "MasterAdjSignal"
output: html_document
date: "2024-03-14"
---

```{r}
library(tidyquant)
library(tidyr)
library(fredr)
library(purrr)
library(ggplot2)
library(rvest)
library(readxl)
options(scipen=999)
library(jsonlite)
library(tidyverse)
library(lubridate)
library(plotly)
library(TTR)
```

#### To check release schdeules

```{r}

# # base sheet (with the release schedule numbers)
# https://api.stlouisfed.org/fred/releases?api_key=d1ddfc3727527d3ca0b0ddebd7e9dade


FREDrelease <- function(seriesID, apiKey, seriesName){
  fredUrl <- sprintf("https://api.stlouisfed.org/fred/release/dates?release_id=%s&api_key=%s&file_type=json", seriesID, apiKey)

  Jdata <- fromJSON(fredUrl)

  seriesDf <- as.data.frame(Jdata$release_dates)
  
  seriesDf <- seriesDf %>%
    mutate(seriesName = seriesName)
  
  return(seriesDf)
}


unempR <- FREDrelease(50, 'd1ddfc3727527d3ca0b0ddebd7e9dade', "UNRATE")

permitR <- FREDrelease(148, 'd1ddfc3727527d3ca0b0ddebd7e9dade', "PERMIT")

umcsentR <- FREDrelease(91, 'd1ddfc3727527d3ca0b0ddebd7e9dade', "UMCSENT")

dgorderR <- FREDrelease(95, 'd1ddfc3727527d3ca0b0ddebd7e9dade', "DGORDER")

zillowR <- FREDrelease(503, 'd1ddfc3727527d3ca0b0ddebd7e9dade', "ZillowIndex")


```

## Master Monthly Econ Data

```{r}

# Global geopol risk index
gpr <- haven::read_dta('https://www.matteoiacoviello.com/gpr_files/data_gpr_export.dta')

refDate <- as.Date("1985-01-01")

gpr <- gpr %>% 
  select(month, GPR) %>% 
  drop_na() %>% 
  mutate(date = refDate %m+% months(month - 300)) %>% 
  select(date, value = GPR) %>% 
  mutate(series_id = "GPR") %>% 
  mutate(dateRel = date + months(1) + days(1)) %>% 
  filter(date >= '2000-01-01')

moMastSeriesSym <- c("HOUST", "UMCSENT", "PCE", "CPIAUCSL", "UNRATE", "USAUCSFRCONDOSMSAMID", "DGORDER", "A33DNO", "TRFVOLUSM227SFWA", "RAILFRTINTERMODAL", "REALLN")
# "USAUCSFRCONDOSMSAMID" Zillow housing price index

moMastSeries <- tidyquant::tq_get(moMastSeriesSym,
                            get = "economic.data", 
                            from = "2000-01-01", 
                            to = Sys.Date()) %>%
  rename(series_id = symbol, value = price) %>%
  mutate(dateRel = case_when(series_id == "HOUST" ~ date + months(2) - days(1),
                             series_id == "UMCSENT" ~ date + months(2) - days(1),
                             series_id == "PCE" ~ date + months(2) - days(1),
                             series_id == "CPIAUCSL" ~ date + months(2) - days(1),
                             series_id == "UNRATE" ~ date + months(2) - days(1),
                             series_id == "USAUCSFRCONDOSMSAMID" ~ date + months(2) - days(1),
                             series_id == "DGORDER" ~ date + months(3) - days(1),
                             series_id == "TRFVOLUSM227SFWA" ~ date + months(3) - days(1),
                             series_id == "A33DNO" ~ date + months(3) - days(1),
                             series_id == "RAILFRTINTERMODAL" ~ date + months(3) - days(1),
                             series_id == "REALLN" ~ date + months(3) - days(1),
                             TRUE ~ NA)) 

moMastSeries <- rbind(moMastSeries, gpr)

moMastSeries <- moMastSeries %>%
  mutate(monthRel = format(dateRel, "%m-%Y")) %>%
  mutate(quarterRel = paste0(year(dateRel), "-", quarter(dateRel))) %>% 
  group_by(series_id) %>% 
  mutate(logDeltaMo = log(value/lag(value)),
         twoMA = rollapply(value, 2, mean, fill = NA, align = "right"),
         fiveMA = rollapply(value, 5, mean, fill = NA, align = "right"),
         threeROC = ROC(value, n = 3),
         sixROC = ROC(value, n = 6),
         YoY = (value - lag(value, 12))/lag(value, 12)) %>%
  mutate(xOver = case_when(twoMA >= fiveMA  ~ 1,
                           twoMA < fiveMA ~ -1)) %>% 
  drop_na() %>% 
  ungroup() %>% 
  filter(dateRel >= "2013-01-01",
         dateRel < "2024-01-01")


# Final
moMastSeries 

```
## Master Daily Interest Rate Data

```{r}
dayIntMastSeriesSym <- c("DGS3MO", "DGS2", "DGS10", "T10Y2Y")

dayIntMastSeries <- tidyquant::tq_get(dayIntMastSeriesSym,
                            get = "economic.data", 
                            from = "2000-01-01", 
                            to = Sys.Date()) %>%
  rename(series_id = symbol, value = price) %>%
  mutate(dateRel = date + 1) %>% 
  drop_na()

dayIntMastSeries <- dayIntMastSeries %>%
  mutate(monthRel = format(dateRel, "%m-%Y")) %>%
  mutate(quarterRel = paste0(year(dateRel), "-", quarter(dateRel))) %>% 
  group_by(series_id) %>% 
  mutate(logDeltaMo = log(value/lag(value)),
         twoMA = rollapply(value, 2, mean, fill = NA, align = "right"),
         fiveMA = rollapply(value, 5, mean, fill = NA, align = "right"),
         threeROC = ROC(value, n = 3),
         sixROC = ROC(value, n = 6),
         fiveYrAvg = rollapply(value, 1260, mean, fill = NA, align = "right")) %>%
  mutate(xOver = case_when(twoMA >= fiveMA  ~ 1,
                           twoMA < fiveMA ~ -1)) %>% 
  drop_na() %>% 
  ungroup() %>% 
  filter(dateRel >= "2013-01-01",
         dateRel < "2024-01-01")
 
# Final 
dayIntMastSeries


```
```{r}
dayMastPriceSym  = c("HG=F", "GC=F", "PA=F", "SI=F", "CL=F", "NG=F")


dayMastPrice <- tidyquant::tq_get(dayMastPriceSym, 
                            get = "stock.prices", 
                            from = "2000-01-01", 
                            to = Sys.Date()) %>%
  rename(series_id = symbol) %>%
  mutate(dateRel = date + 1) %>% 
  select(series_id, date, value = adjusted, dateRel) %>% 
  drop_na()


dayMastPrice <- dayMastPrice %>%
  mutate(monthRel = format(dateRel, "%m-%Y")) %>%
  mutate(quarterRel = paste0(year(dateRel), "-", quarter(dateRel))) %>% 
  group_by(series_id) %>% 
  mutate(logDeltaMo = log(value/lag(value)),
         oneMA = rollapply(value, 21, mean, fill = NA, align = "right"),
         fourMA = rollapply(value, 84, mean, fill = NA, align = "right"),
         threeROC = ROC(value, n = 3),
         sixROC = ROC(value, n = 6)) %>%
  mutate(xOver = case_when(oneMA >= fourMA  ~ 1,
                           oneMA < fourMA ~ -1)) %>% 
  drop_na() %>% 
  ungroup() %>% 
  filter(dateRel >= "2013-01-01",
         dateRel < "2024-01-01")
 
# Final 
dayMastPrice 

```

## Energy
```{r}
energySigMo <- moMastSeries %>% 
  filter(series_id %in% c("A33DNO", "TRFVOLUSM227SFWA", "GPR")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY)

energySigDay <- dayMastPrice %>% 
  filter(series_id %in% c("CL=F")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-oneMA, - fourMA)

energySig <- rbind(energySigMo, energySigDay)

energySig <- energySig %>% 
  group_by(quarterRel) %>% 
  summarise(sig = sum(xOverSig)/n()) %>% 
  mutate(sector = 'Energy')

```

#Materials

```{r}

materialsSigMo <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ 1, 
                            fiveYrAvg < value ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) %>% 
  mutate(xOverSig = 0)

materialsSigDay <- dayMastPrice %>% 
  filter(series_id %in% c("HG=F", "GC=F")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-oneMA, - fourMA) %>% 
  mutate(avgSig = 0)

materialsSig <- rbind(materialsSigMo, materialsSigDay)

materialsSig <- materialsSig %>% 
  mutate(sig = avgSig + xOverSig) %>% 
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Materials')
  
```

# Industrials

```{r}

industrialSigMo <- moMastSeries %>% 
  filter(series_id %in% c("DGORDER", "RAILFRTINTERMODAL", "GPR")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY) %>% 
  mutate(avgSig = 0)


industrialSigDay <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ 1, 
                            fiveYrAvg < value ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) %>% 
  mutate(xOverSig = 0)


industrialSig <- rbind(industrialSigMo, industrialSigDay)

industrialSig <- industrialSig %>% 
  mutate(sig = avgSig + xOverSig) %>% 
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Industrials')
```

# Consumer Discretionary

```{r}
conDiscSig <- moMastSeries %>% 
  filter(series_id %in% c("PCE", "UNRATE")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY) %>% 
  mutate(xOverSig = case_when(series_id == "UNRATE" ~ xOverSig*-1,
                              TRUE ~ xOverSig))

conDiscSig <- conDiscSig %>% 
  mutate(sig = xOverSig) %>% 
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Discretionary')

```
# Consumer Staples
```{r}
conStapSigMo <- moMastSeries %>% 
  filter(series_id %in% c("UNRATE")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY) %>% 
  mutate(avgSig = 0)


conStapSigDay <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ -1, 
                            fiveYrAvg < value ~ 1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) %>% 
  mutate(xOverSig = 0)


conStapSig <- rbind(conStapSigMo, conStapSigDay)


conStapSig <- conStapSig %>% 
  mutate(sig = xOverSig + avgSig) %>% 
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Staples')

```
#Healthcare

```{r}
healthSigMo <- moMastSeries %>% 
  filter(series_id %in% c("CPIAUCSL")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(aboveTarg = case_when(YoY > .025 ~ 1,
                               YoY <= .025 ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY) %>% 
  mutate(invertSig = 0)


healthSigDay <- dayIntMastSeries %>% 
  filter(series_id %in% c("T10Y2Y")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(invertSig = case_when(value >= 0 ~ 0, 
                            value < 0 ~ 1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) %>% 
  mutate(aboveTarg = 0)


healthSig <- rbind(healthSigMo, healthSigDay)


healthSig <- healthSig %>% 
  mutate(sig = aboveTarg + invertSig) %>% 
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Healthcare')

```
# Finacials

```{r}

finSig <- moMastSeries %>% 
  filter(series_id %in% c("REALLN", "HOUST")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY) 


finSig <- finSig %>% 
  mutate(sig = xOverSig) %>%
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Financials')

```


# Infotech
```{r}


infoTechSigMo <- moMastSeries %>% 
  filter(series_id %in% c("PCE")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(xOverSig = xOver) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -YoY) %>% 
  mutate(avgSig = 0)

infoTechSigDay <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ 1, 
                            fiveYrAvg < value ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) %>% 
  mutate(xOverSig = 0)


infoTechSig <- rbind(infoTechSigMo, infoTechSigDay)


infoTechSig <- infoTechSig %>% 
  mutate(sig = xOverSig + avgSig) %>%
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Infotech')


```
# Realestate
```{r}

realSig <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ 1, 
                            fiveYrAvg < value ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) 


realSig <- realSig %>% 
  mutate(sig = avgSig) %>%
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Realestate')




```

 [1] "Healthcare"    "Materials"     "Industrials"   "Discretionary" "Infotech"     
 [6] "Staples"       "Utilities"     "Financials"    "Energy"        "Communication"
[11] "Realestate" 


# Communications

```{r}

comSig <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ 1, 
                            fiveYrAvg < value ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) 


comSig <- comSig %>% 
  mutate(sig = avgSig) %>%
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Communication')

```
```{r}
utilSig <- dayIntMastSeries %>% 
  filter(series_id %in% c("DGS2")) %>% 
  group_by(quarterRel, series_id) %>% 
  filter(dateRel == max(dateRel)) %>% 
  mutate(avgSig = case_when(fiveYrAvg >= value ~ 1, 
                            fiveYrAvg < value ~ -1)) %>% 
  ungroup() %>% 
  select(-twoMA, - fiveMA, -fiveYrAvg) 


utilSig <- utilSig %>% 
  mutate(sig = avgSig) %>%
  group_by(quarterRel) %>% 
  summarise(sig = sum(sig)/n()) %>% 
  mutate(sector = 'Utilities')


```



```{r}
rbind(comSig, realSig,
      infoTechSig, finSig,
      conStapSig, conDiscSig,
      healthSig, industrialSig,
      materialsSig, energySig,
      utilSig) %>% 
  group_by(quarterRel) %>% 
  mutate(sigSum = sum(sig),
         weightSec = sig/sigSum) %>% 
  filter(quarterRel == "2013-1")
```




